apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-1
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-1
  template:
    metadata:
      labels:
        app: hello-world-1
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: hello-world-html-1

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: hello-world-1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html-1
data:
  index.html: |
    <html>
      <head><title>Hello World 1</title></head>
      <body><h1>Hello World from Kubernetes - Instance 1!</h1></body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-2
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-2
  template:
    metadata:
      labels:
        app: hello-world-2
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: hello-world-html-2

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: hello-world-2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html-2
data:
  index.html: |
    <html>
      <head><title>Hello World 2</title></head>
      <body><h1>Hello World from Kubernetes - Instance 2!</h1></body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-3
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-3
  template:
    metadata:
      labels:
        app: hello-world-3
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: hello-world-html-3

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-3
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: hello-world-3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html-3
data:
  index.html: |
    <html>
      <head><title>Hello World 3</title></head>
      <body><h1>Hello World from Kubernetes - Instance 3!</h1></body>
    </html>
